# ─── docker-compose.yml ───
version: "3.9"

services:
  canecestry:
    build: .
    ports:
      - "8050:8050"          # hostPort:containerPort
    volumes:
      - .:/app               # map repo → /app (live-reload)
      - ./pedigree/user_data:/app/pedigree/user_data  # allow user to edit this folder
    container_name: canecestry_dev